apiVersion: v1
kind: Service
metadata:
  name: webapp-service
  namespace: java-webapp
spec:
  selector:
    app: docker-java-sample-webapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort